// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// precision_decomp_sparse
arma::sp_mat precision_decomp_sparse(List cov_par, const arma::mat& X, const IntegerMatrix& NN, const arma::mat& locs, int start);
RcppExport SEXP _VecchiaCensored_precision_decomp_sparse(SEXP cov_parSEXP, SEXP XSEXP, SEXP NNSEXP, SEXP locsSEXP, SEXP startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cov_par(cov_parSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type NN(NNSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type locs(locsSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    rcpp_result_gen = Rcpp::wrap(precision_decomp_sparse(cov_par, X, NN, locs, start));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VecchiaCensored_precision_decomp_sparse", (DL_FUNC) &_VecchiaCensored_precision_decomp_sparse, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_VecchiaCensored(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
