#' VecchiaCensored: Vecchia Approximation for Censored Spatial Data
#'
#' This package implements Vecchia approximation methods for spatial
#' statistics with censored data. It provides efficient algorithms using
#' sparse matrix decompositions and Rcpp for computational performance.
#'
#' @docType package
#' @name VecchiaCensored
#' @useDynLib VecchiaCensored, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @importFrom stats pnorm dnorm rnorm lm var optim
#' @import GpGp
#' @import Matrix
#' @import Rfast
#' @import cmdstanr
#' @import bayesplot
"_PACKAGE"


# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

precision_decomp_sparse <- function(cov_par, X, NN, locs, start = 1L) {
    .Call('_VecchiaCensored_precision_decomp_sparse', PACKAGE = 'VecchiaCensored', cov_par, X, NN, locs, start)
}

